name: Trigger Another Workflow

on:
  workflow_dispatch:
    inputs:
      parameter1:
        description: 'Input parameter 1'
        required: true
      parameter2:
        description: 'Input parameter 2'
        required: true

jobs:
  call-another-workflow:
    uses: abz/github-maven-app/.github/workflows/target-workflow.yml@main
    with:
      parameter1: ${{ github.event.inputs.parameter1 }}
      parameter2: ${{ github.event.inputs.parameter2 }}
